//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.21 at 07:37:33 PM ART 
//


package com.plugtree.bi.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for diagramType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="diagramType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="plane" type="{http://www.plugtree.com/spec/EPMN/20120921/MODEL}diagramPlaneType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "diagramType", propOrder = {
    "plane"
})
public class DiagramType {

    @XmlElement(required = true)
    protected DiagramPlaneType plane;

    /**
     * Gets the value of the plane property.
     * 
     * @return
     *     possible object is
     *     {@link DiagramPlaneType }
     *     
     */
    public DiagramPlaneType getPlane() {
        return plane;
    }

    /**
     * Sets the value of the plane property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiagramPlaneType }
     *     
     */
    public void setPlane(DiagramPlaneType value) {
        this.plane = value;
    }

}
