//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.21 at 07:37:33 PM ART 
//


package com.plugtree.bi.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for networkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="networkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="channel" type="{http://www.plugtree.com/spec/EPMN/20120921/MODEL}networkChannelType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="producer" type="{http://www.plugtree.com/spec/EPMN/20120921/MODEL}networkProducerType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="consumer" type="{http://www.plugtree.com/spec/EPMN/20120921/MODEL}networkConsumerType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="processor" type="{http://www.plugtree.com/spec/EPMN/20120921/MODEL}networkProcessorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="repository" type="{http://www.plugtree.com/spec/EPMN/20120921/MODEL}networkRepositoryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="connector" type="{http://www.plugtree.com/spec/EPMN/20120921/MODEL}networkConnectorType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.plugtree.com/spec/EPMN/20120921/MODEL}id use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "networkType", propOrder = {
    "channel",
    "producer",
    "consumer",
    "processor",
    "repository",
    "connector"
})
public class NetworkType {

    protected List<NetworkChannelType> channel;
    protected List<NetworkProducerType> producer;
    protected List<NetworkConsumerType> consumer;
    protected List<NetworkProcessorType> processor;
    protected List<NetworkRepositoryType> repository;
    protected List<NetworkConnectorType> connector;
    @XmlAttribute(namespace = "http://www.plugtree.com/spec/EPMN/20120921/MODEL", required = true)
    protected String id;

    /**
     * Gets the value of the channel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkChannelType }
     * 
     * 
     */
    public List<NetworkChannelType> getChannel() {
        if (channel == null) {
            channel = new ArrayList<NetworkChannelType>();
        }
        return this.channel;
    }

    /**
     * Gets the value of the producer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the producer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProducer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkProducerType }
     * 
     * 
     */
    public List<NetworkProducerType> getProducer() {
        if (producer == null) {
            producer = new ArrayList<NetworkProducerType>();
        }
        return this.producer;
    }

    /**
     * Gets the value of the consumer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the consumer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConsumer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkConsumerType }
     * 
     * 
     */
    public List<NetworkConsumerType> getConsumer() {
        if (consumer == null) {
            consumer = new ArrayList<NetworkConsumerType>();
        }
        return this.consumer;
    }

    /**
     * Gets the value of the processor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkProcessorType }
     * 
     * 
     */
    public List<NetworkProcessorType> getProcessor() {
        if (processor == null) {
            processor = new ArrayList<NetworkProcessorType>();
        }
        return this.processor;
    }

    /**
     * Gets the value of the repository property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repository property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepository().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkRepositoryType }
     * 
     * 
     */
    public List<NetworkRepositoryType> getRepository() {
        if (repository == null) {
            repository = new ArrayList<NetworkRepositoryType>();
        }
        return this.repository;
    }

    /**
     * Gets the value of the connector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkConnectorType }
     * 
     * 
     */
    public List<NetworkConnectorType> getConnector() {
        if (connector == null) {
            connector = new ArrayList<NetworkConnectorType>();
        }
        return this.connector;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
